/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programacion.dam.tarea7.menu;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import programacion.dam.tarea7.beans.Articulo;
import programacion.dam.tarea7.util.Util;

/**
 *
 * @author Roach
 */
public class DatosFichero extends javax.swing.JFrame {

    // Atributos
    private DefaultTableModel modelo;
    
    
    // Constructores
    public DatosFichero() {
        initComponents();
        
                // Pintamos los atributos mas importantes de los articulos.
        String[] columnas = {"Codigo", "Descripción", "Precio", "Descuento", "IVA"};
        modelo = new DefaultTableModel(null, columnas);
        
        tablaArticulos.setModel(modelo);
        
        // Cargamos la lista de articulos temporal.
        this.cargarListaFichero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bBuscar = new javax.swing.JButton();
        bListaCompleta = new javax.swing.JButton();
        tCodigoBuscar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArticulos = new javax.swing.JTable();
        bModificar = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        BVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Buscar por Codigo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Codigo Articulo");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bBuscar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        bListaCompleta.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bListaCompleta.setText("Lista Completa");
        bListaCompleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListaCompletaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(tCodigoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bBuscar)
                .addGap(108, 108, 108))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(bListaCompleta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar)
                    .addComponent(tCodigoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(bListaCompleta)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "ARTICULOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 14))); // NOI18N

        tablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaArticulos);

        bModificar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bModificar.setText("Modificar");
        bModificar.setToolTipText("");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        bBorrar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        BVolver.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        BVolver.setText("Volver");
        BVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BVolver)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(BVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /**
     * Acción que enlaza con la ventana modificar articulo.
     * @param evt 
     */
    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        if(tablaArticulos.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Debe de seleccionar un articulo para modificar.",
                "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String codigoArticulo = tablaArticulos.getValueAt(tablaArticulos.getSelectedRow(), 0).toString().trim();
        
        ModificarArticulo modificarArticulo = new ModificarArticulo(this, codigoArticulo, "FICHERO");
        
        modificarArticulo.setVisible(true);
    }//GEN-LAST:event_bModificarActionPerformed

    /**
     * Acción del botón volver, con el que cerraremos la ventana Datos Fichero
     * @param evt 
     */
    private void BVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVolverActionPerformed
        // Con this.dispose() cerramos la ventana actual y la dejamos limpia.
        this.dispose();        
    }//GEN-LAST:event_BVolverActionPerformed

    /**
     * Acción que muestra la lista de articulos del fichero completa
     * @param evt 
     */
    private void bListaCompletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListaCompletaActionPerformed
        borrarTabla();   
        cargarListaFichero(); 
    }//GEN-LAST:event_bListaCompletaActionPerformed

    /**
     * Acción que borra el articulo del fichero.
     * @param evt 
     */
    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        // Verificamos que se ha seleccionado un articulo para borrarlo de la lista del fichero
        // y la tabla.
        if(tablaArticulos.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Debe de seleccionar un articulo para borrar",
                "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
                // Recogemos el codigo del articulo seleccionado.
        String codigoAuxiliar = tablaArticulos.getValueAt(tablaArticulos.getSelectedRow(), 0).toString().trim();
                
        // Borramos de la tabla
        modelo.removeRow(tablaArticulos.getSelectedRow());
                
        // Borramos de la lista del fichero.
        Util.borrarArticuloFichero(codigoAuxiliar);
    }//GEN-LAST:event_bBorrarActionPerformed
 
    /**
     * Acción que filtra los articulos de la tabla y pinta el articulo coincidente con
     * el codigo pasado.
     * @param evt 
     */
    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        if(tCodigoBuscar.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "Debe de insertar el codigo del articulo a buscar.",
                "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String codigoAux = tCodigoBuscar.getText().trim();
        
        // Buscamos el articulo en la lista temporal
        Articulo articulo = Util.buscarArticuloPorCodigo(codigoAux, Util.listaArticulos);
        
        if(null == articulo){
            JOptionPane.showMessageDialog(null, "El codigo introducido no corresponde a ningun articulo.",
                "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }else{
            // Borramos los articulos que estuviesen en la tabla.
            borrarTabla();
            
            String [] fila = {articulo.getCodArticulo(), articulo.getDescripcion(), articulo.getPrecio().toString().concat(" Euros"),
                                    articulo.getDescuento().toString().concat(" Euros"), articulo.getIva().toString().concat("%")};
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_bBuscarActionPerformed

// ***************************************************************************************************
// ************************************ Utilidades de la Clase ***************************************
// ***************************************************************************************************
    
    /**
     * Método auxiliar que limpia la tabla.
     */
    private void borrarTabla(){
        int longitud = tablaArticulos.getRowCount()-1;  
        for(int i = longitud; i >= 0; i--){
            modelo.removeRow(i);
        }
    }
    
    /**
     * Método que carga los articulos que se encuentran en la lista temporal,
     * y recoge los datos mas importantes para cargarlos en la tabla.
     */
    public void cargarListaFichero(){
        // Liampiamos la tabla al cargar nuevos articulos, para evitar duplicidades.
        borrarTabla();
        
        ArrayList<Articulo> listaFichero = Util.listarArticulosFichero();
        
        for(Articulo articulo : listaFichero){
            // Creamos un array para recoger los datos necesarios de cada articulo.
           String [] fila = {articulo.getCodArticulo(), articulo.getDescripcion(), articulo.getPrecio().toString().concat(" Euros"),
                                    articulo.getDescuento().toString().concat(" Euros"), articulo.getIva().toString().concat("%")};
            
            // Añadimos a la tabla los datos del articulo actual.
            modelo.addRow(fila);
        }
    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BVolver;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bListaCompleta;
    private javax.swing.JButton bModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCodigoBuscar;
    private javax.swing.JTable tablaArticulos;
    // End of variables declaration//GEN-END:variables
}
